version: 2.0

install_hex_rebar: &install_hex_rebar

jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.3-node-browsers
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_DB: explorer_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - checkout
      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force
      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock
      - restore_cache:
          keys:
            - v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
            - v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
            - v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run: mix deps.get

      - restore_cache:
          keys:
            - v1-npm-install-{{ .Branch }}-{{ checksum "apps/discotex_web/assets/package-lock.json" }}
            - v1-npm-install-{{ .Branch }}
            - v1-npm-install

      - run:
          command: npm install
          working_directory: "apps/discotex_web/assets"

      - save_cache:
          key: v1-npm-install-{{ .Branch }}-{{ checksum "apps/discotex_web/assets/package-lock.json" }}
          paths: "apps/discotex_web/assets/node_modules"

      - save_cache:
          key: v1-npm-install-{{ .Branch }}
          paths: "apps/discotex_web/assets/node_modules"

      - save_cache:
          key: v1-npm-install
          paths: "apps/discotex_web/assets/node_modules"

      - run: mix compile

      - save_cache:
          key: v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
      - save_cache:
          key: v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "mix.exs" }}
          paths:
            - deps
            - _build
      - save_cache:
          key: v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - deps
            - _build

      - run:
          name: Build assets
          command: node node_modules/webpack/bin/webpack.js --mode development
          working_directory: "apps/discotex_web/assets"

      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix do ecto.create, ecto.migrate && mix test

      - store_artifacts:
          path: apps/discotex_web/screenshots
          destination: screenshots

      - persist_to_workspace:
          root: .
          paths:
            - .circleci
            - .credo.exs
            - .formatter.exs
            - .git
            - .gitignore
            - ELIXIR_VERSION.lock
            - OTP_VERSION.lock
            - _build
            - apps
            - config
            - deps
            - mix.exs
            - mix.lock

workflows:
  version: 2
  primary:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
